[package]
name = "Day1"
version = "0.1.0"
authors = ["Rob Schaefer <rob@linkage.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
